### ISSUE TITLE
Everything is playing at 720p

### ISSUE THREAD

**Issue by romanar** [vladikoff/netflix-1080p-firefox#1]
Hi, I wrote my own Firefox Add-on based on https://github.com/truedread/netflix-1080p and It did not worked as everything was playing at 720p. I though that I wrote it wrong as this was my first try at Firefox Add-ons. However, Later I tried your version and It also played at the same resolution and I did cleared the Cached Web Content.
![screen shot 2018-02-11 at 1 26 39 pm](https://user-images.githubusercontent.com/32021606/36076806-4d4f89f2-0f2f-11e8-805f-98c86a2e42f6.png)
`manifest.json` 
```
{

  "manifest_version": 2,
  "name": "NETFLIX-1080P",
  "version": "1.0",

  "web_accessible_resources": [
    "cadmium-playercore-5.0008.544.011-1080p.js"
  ],

  "content_scripts": [
    {
      "matches": ["*://assets.nflxext.com/en_us/ffe/player/html/*",
        "*://www.assets.nflxext.com/en_us/ffe/player/html/*",
        "*://netflix.com/watch/*",
        "*://www.netflix.com/watch/*"],
      "js": ["background.js"]
    }
  ],

  "permissions": [
    "tabs",
    "webRequest",
    "webNavigation",
    "webRequestBlocking",
    "management"
  ]

}
```
`background.js`
```
browser.webRequest.onBeforeRequest.addListener(

  function(details) {
    return {
      redirectUrl: browser.extension.getURL("cadmium-playercore-5.0008.544.011-1080p.js")
    };
  }, {
    urls: [
      "*://assets.nflxext.com/en_us/ffe/player/html/*",
      "*://www.assets.nflxext.com/en_us/ffe/player/html/*"
    ]
  }, ["blocking"]
);
```
## Environment
- **Name of Browser**: Firefox
- **Version**: 58.0.2
- **Build ID**: 20180206200532
- **User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0

Edit: Sorry for bothering you. I got your Add-on working perfectly. You can go ahead close this issue.

**Comment by vladikoff** [comment]
no worries :)
