### ISSUE TITLE
Netflix error code M7111-1309

### ISSUE THREAD

**Issue by TheRealBecks** [vladikoff/netflix-1080p-firefox#10]
We've used Ubuntu 16.04 with Firefox and it worked great for months. Four days ago we switched to Opensuse Tumbleweed and it also worked flawlessly. But since two days we get the error M7111-1309.

We're in the middle of an episode of 'Luke Cage' and can watch that episode and also 'How I met your mother' is working great, but everything else isn't working anymore.

Not working:

    Brooklyn Nine-Nine
    iZombie

That's what the Firefox developer console shows when I want to watch Brooklyn Nine-Nine:

    Manifest locked to Edge (or not available in 1080p) cadmium-playercore-6.0009.934.051.js:34560:37
    Getting Edge manifest cadmium-playercore-6.0009.934.051.js:34561:37
    Acquisition successful, commence playback cadmium-playercore-6.0009.934.051.js:34563:37

Watching the test pattern works great in 1080p. Can I provide any more information to help you out?

**Comment by NovaPrima** [comment]
This is happening to me for 20th Century Fox shows: American Crime Story, How I Met Your Mother, Homeland, and others. The thing is though that for whatever reason, this extension never let them go higher than 1080p anyway.

**Comment by Perpetucake** [comment]
Receiving this error with every single show as of a few days ago. Same issue with the chrome extension this is based off of.

**Comment by NoXPhasma** [comment]
I get an error as well, it's slightly different: M7111-1331 and it happens with this Addon as well with ten Chrome Addon. It happens with every single movie/show. Even those of Netflix, which usually worked best. Even the [test video](https://www.netflix.com/watch/80018585?trackId=14277281&tctx=0%2C0%2C721b889b-ed99-4966-816c-7f48f8e3f26e-124763365) crashes.

**Comment by reox** [comment]
I get this error too for several movies: Arrival, Passenger, the martian, ...
Test video is working, also Pine Gap and Altered Carbon plays in FHD.
Suicide Squad gives me 960x540 resolution, breaking bad 1280x720

Mozilla Firefox 64.0

**Comment by TheRealBecks** [comment]
Netflix is working natively under Linux
