### ISSUE TITLE
m7363-1260 unexpected error

### ISSUE THREAD

**Issue by rawsh** [vladikoff/netflix-1080p-firefox#2]
I've rebooted + reloaded browser + cleared cookies.
Ubuntu Linux + Firefox latest. All titles, works without extension

**Comment by fosspill** [comment]
Indeed. Doesn't work at all sadly :(

**Comment by vladikoff** [comment]
Could you paste / screenshot the error when you go to https://www.netflix.com/watch/80018585?trackId=14277281&tctx=0%2C0%2C721b889b-ed99-4966-816c-7f48f8e3f26e-124763365 ?

**Comment by fosspill** [comment]
What the... After watching that it works everywhere.
I did change my language to English before testing, might be dependent on that?

**Comment by vladikoff** [comment]
@fosspill there is a setting to intercept only `en_us` locales https://github.com/vladikoff/netflix-1080p-firefox/blob/master/src/background.js#L9 

Might have to check if other locales need to be added to that intercept

**Comment by Tyestor** [comment]
That would be ideal, as not everyone on Earth lives in The U.S.

**Comment by rawsh** [comment]
![peek 2018-02-13 08-15](https://user-images.githubusercontent.com/7035671/36154165-28a81188-1096-11e8-8d94-19bc6d5d5ab3.gif)

**Comment by fosspill** [comment]
^ Exactly what I had at the start, but now it's magically working perfectly. Unsure of what caused it. Some kind of cache?

**Comment by thomastjeffery** [comment]
I'm having this problem too. Firefox on Archlinux.

**Comment by vladikoff** [comment]
> I did change my language to English before testing

1.3 is out that should support all locales, please let me know if there are issues

**Comment by rawsh** [comment]
@vladikoff Still getting the error

**Comment by fosspill** [comment]
I got the error again yesterday. Had to turn the addon off, then start a video, start addon and then refresh the video. Something is weird with the addon.

**Comment by utack** [comment]
Same here.  
Watching the test clip linked above "enabled" playback, but it does seem weird  
Firefox in Arch Linux

**Comment by kaimast** [comment]
Had the same problem. Only removing the Add-On resolved it.

**Comment by utack** [comment]
I believe we are seeing a new error now, as Netflix moves to VP9 and something has changed.

**Comment by vladikoff** [comment]
Try now with latest version

**Comment by kaimast** [comment]
Still does not work for me.
