### ISSUE TITLE
[suggestion] 1080p and 2160p  possible?

### ISSUE THREAD

**Issue by Hoerli1337** [vladikoff/netflix-1080p-firefox#3]
Can you add support for 2160p to see a 4K-Video on a 1440p or 1080p Monitor?
That would be really great :)
With the test video - which is available in 4K according to the title - the add-on only switches to a maximum of 1080p.

**Comment by vladikoff** [comment]
@Hoerli1337 the 4k situation is not great :( See this thread for more details https://www.reddit.com/r/netflix/comments/7wrr78/i_made_a_chrome_extension_to_force_netflix_to/du32tiq/ AND https://www.reddit.com/r/netflix/comments/7wrr78/i_made_a_chrome_extension_to_force_netflix_to/

**Comment by Hoerli1337** [comment]
ohh :(
