### ISSUE TITLE
NetFlix changes JS code.. Firefox loops with infinite recursion

### ISSUE THREAD

**Issue by Cyborgscode** [vladikoff/netflix-1080p-firefox#40]
today FF76 stopped playing NetFlix streams, and stopped with an infinite recursion in the playercode.

After disabling the 1080p addon, code worked again. 
reenabling the addon did reveal a different bug. 

ATM: the 1.9 version of this addon is not useable.

**Comment by Cyborgscode** [comment]
add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21586
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590
    add https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0022.905.051.js:21590

**Comment by Techassi** [comment]
Same here.

**Comment by Termuellinator** [comment]
can confirm :(

**Comment by mikeloeven** [comment]
Confirmed

**Comment by hashar** [comment]
Same with Firefox ESR 68.8.0. I guess Netflix has changed something.

This project is for the Firefox extension, it is based on https://github.com/truedread/netflix-1080p/ which has a similar issue: https://github.com/truedread/netflix-1080p/issues/90

**Comment by d-sfounis** [comment]
Confirming, not working anymore

**Comment by Cyborgscode** [comment]
ID-A) content_script.js

script_urls = [
    'https://cdn.rawgit.com/ricmoo/aes-js/master/index.js',
    'https://cdn.rawgit.com/Caligatio/jsSHA/blob/v2/src/sha.js'
]

Would solve the first problem with sha calculations, as the master tree switched to TypeScript, BUT rawgithub refused to server the file. 

I have no idea how to reference a local copy of the sha.js in this file. 
I don't think, blind replacement with "browser.extension.getURL("sha.js")" won't work here.

**Comment by Cyborgscode** [comment]
ok, replacement seemed to have worked, but due to CORS player does not load:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at moz-extension://ae9fba4e-fc78-444e-a5fa-d5fa3519fd48/cadmium-playercore-1080p.js. (Reason: CORS request not http

**Comment by Cyborgscode** [comment]
the CORS problem seems to be major issue here.

**Comment by SinTan1729** [comment]
https://github.com/truedread/netflix-1080p/pull/95

People who understand these things, maybe take a look here?
