### ISSUE TITLE
cadmium-playercore-1080p.js too large to parse.

### ISSUE THREAD

**Issue by rlevet** [vladikoff/netflix-1080p-firefox#42]
Can't get a signature

**Comment by Brandhand** [comment]
Just replace whitespaces on the beginning of every line:

`sed -E 's/^\s+//g' cadmium-playercore-1080p.js > small_cadmium-playercore-1080p.js`
It gets small enough, so mozilla won't complain on signing.

**Comment by rlevet** [comment]
> Just replace whitespaces on the beginning of every line:
> 
> `sed -E 's/^\s+//g' cadmium-playercore-1080p.js > small_cadmium-playercore-1080p.js`
> It gets small enough, so mozilla won't complain on signing.
I am on windows

**Comment by rlevet** [comment]
[netflix-1080p-firefox-fix@vladikoff-1.9.1.zip](https://github.com/vladikoff/netflix-1080p-firefox/files/4678551/netflix-1080p-firefox-fix%40vladikoff-1.9.1.zip)

Here is the signed version (I named it 1.9.1 because I already had an older one)
