### ISSUE TITLE
Addon has been taken down?

### ISSUE THREAD

**Issue by Eric-Bwr** [vladikoff/netflix-1080p-firefox#67]
Welp, the link aint working, firefox says it cant the addon :(

**Comment by xerhaxs** [comment]
The addon has been removed by mozilla. You could try to install it manually.

**Comment by Eric-Bwr** [comment]
Alrightie, how would I go about that? I have never worked myself with addons. Do I use web-ext to install it or what tool would you prefer? @xerhaxs

**Comment by xerhaxs** [comment]
Here is a solution / download of a compiled and signed version of the addon: https://github.com/vladikoff/netflix-1080p-firefox/issues/63

**Comment by Eric-Bwr** [comment]
It worked wonderfully. Thank you so, so much! Do you have, by any chance, one for prime video aswell? :D

**Comment by xerhaxs** [comment]
You are welcome. And sorry, I don't know one for prime Video.

**Comment by Eric-Bwr** [comment]
Verdammt. Alright, thank you anyways 👋
